# -*- encoding: utf-8 -*-

=begin
#Gopad OpenAPI

#API definition for Gopad

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

$LOAD_PATH.push File.expand_path('../lib', __FILE__)
require 'gopad/version'

Gem::Specification.new do |s|
  s.name = 'gopad'
  s.version = Gopad::VERSION
  s.platform = Gem::Platform::RUBY

  s.authors = ['Thomas Boerger']
  s.email = ['thomas@webhippie.de']
  s.homepage = 'https://github.com/gopad/gopad-ruby'
  s.summary = 'Etherpad for markdown with Go'
  s.description = 'OpenAPI client for Gopad'
  s.license = 'Apache-2.0'

  s.files = ['CHANGELOG.md', 'CONTRIBUTING.md', 'DCO', 'README.md', 'LICENSE'] + Dir.glob('lib/**/*')
  s.test_files = Dir.glob('spec/**/*')
  s.require_paths = ['lib']

  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
end
