---
gemAuthor: Thomas Boerger
gemAuthorEmail: thomas@webhippie.de
gemDescription: OpenAPI client for Gopad
gemHomepage: https://github.com/gopad/gopad-ruby
gemLicense: Apache-2.0
gemName: gopad
gemSummary: Etherpad for markdown with Go
gemVersion: 1.16.0
moduleName: Gopad
library: faraday
enablePostProcessFile: true

...
