# #Gopad OpenAPI
#
# API definition for Gopad, Etherpad for markdown with go
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: gopad@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.6.0
#

require 'spec_helper'
require 'json'

# Unit tests for Gopad::TeamApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeamApi' do
  before do
    # run before each test
    @api_instance = Gopad::TeamApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamApi' do
    it 'should create an instance of TeamApi' do
      expect(@api_instance).to be_instance_of(Gopad::TeamApi)
    end
  end

  # unit tests for attach_team_to_user
  # Assign a user to team
  # @param team_id A team identifier or slug
  # @param team_user_params The team user data to attach
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_team_to_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_team
  # Create a new team
  # @param team The team data to create
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'create_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_team
  # Delete a specific team
  # @param team_id A team identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_team_from_user
  # Remove a user from team
  # @param team_id A team identifier or slug
  # @param team_user_params The team user data to delete
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_team_from_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_team_users
  # Fetch all users assigned to team
  # @param team_id A team identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [TeamUsers]
  describe 'list_team_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_teams
  # Fetch all available teams
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [Teams]
  describe 'list_teams test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permit_team_user
  # Update user perms for team
  # @param team_id A team identifier or slug
  # @param team_user_params The team user data to update
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'permit_team_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_team
  # Fetch a specific team
  # @param team_id A team identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'show_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_team
  # Update a specific team
  # @param team_id A team identifier or slug
  # @param team The team data to update
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'update_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
