# Gopad OpenAPI
#
# API definition for Gopad, Etherpad for markdown with go
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: gopad@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.10.0
#

require 'spec_helper'
require 'json'

# Unit tests for Gopad::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = Gopad::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(Gopad::UserApi)
    end
  end

  # unit tests for attach_user_to_group
  # Attach a group to user
  # @param user_id A user identifier or slug
  # @param permit_user_group_request The user group data to permit
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'attach_user_to_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_user
  # Create a new user
  # @param create_user_request The user data to create
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'create_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user
  # Delete a specific user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_user_from_group
  # Unlink a group from user
  # @param user_id A user identifier or slug
  # @param delete_user_from_group_request The user group data to unlink
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'delete_user_from_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_user_groups
  # Fetch all groups attached to user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [ListUserGroups200Response]
  describe 'list_user_groups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users
  # Fetch all available users
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Search query
  # @option opts [String] :sort Sorting column
  # @option opts [String] :order Sorting order
  # @option opts [Integer] :limit Paging limit
  # @option opts [Integer] :offset Paging offset
  # @return [ListUsers200Response]
  describe 'list_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for permit_user_group
  # Update group perms for user
  # @param user_id A user identifier or slug
  # @param permit_user_group_request The user group data to permit
  # @param [Hash] opts the optional parameters
  # @return [Notification]
  describe 'permit_user_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_user
  # Fetch a specific user
  # @param user_id A user identifier or slug
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'show_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user
  # Update a specific user
  # @param user_id A user identifier or slug
  # @param update_user_request The user data to update
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'update_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
