=begin
#Gopad OpenAPI

#API definition for Gopad

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Gopad::TeamUser
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeamUser' do
  before do
    # run before each test
    @instance = Gopad::TeamUser.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamUser' do
    it 'should create an instance of TeamUser' do
      expect(@instance).to be_instance_of(Gopad::TeamUser)
    end
  end
  describe 'test attribute "team_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "perm"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
