=begin
#Gopad OpenAPI

#API definition for Gopad

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Gopad::UserTeamParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserTeamParams' do
  before do
    # run before each test
    @instance = Gopad::UserTeamParams.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserTeamParams' do
    it 'should create an instance of UserTeamParams' do
      expect(@instance).to be_instance_of(Gopad::UserTeamParams)
    end
  end
  describe 'test attribute "team"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "perm"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["user", "admin", "owner"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.perm = value }.not_to raise_error
      # end
    end
  end

end
