# Gopad OpenAPI
#
# API definition for Gopad, Etherpad for markdown with Go
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: gopad@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.13.0
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Gopad::UserAuth
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Gopad::UserAuth do
  let(:instance) { Gopad::UserAuth.new }

  describe 'test an instance of UserAuth' do
    it 'should create an instance of UserAuth' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(Gopad::UserAuth)
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ref"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
