=begin
#Gopad OpenAPI

#API definition for Gopad

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Gopad::ValidationErrorErrors
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Gopad::ValidationErrorErrors do
  let(:instance) { Gopad::ValidationErrorErrors.new }

  describe 'test an instance of ValidationErrorErrors' do
    it 'should create an instance of ValidationErrorErrors' do
      expect(instance).to be_instance_of(Gopad::ValidationErrorErrors)
    end
  end
  describe 'test attribute "field"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
