# Gopad OpenAPI
#
# API definition for Gopad, Etherpad for markdown with Go
#
# The version of the OpenAPI document: 1.0.0-alpha1
# Contact: gopad@webhippie.de
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

# Common files
require 'gopad/api_client'
require 'gopad/api_error'
require 'gopad/version'
require 'gopad/configuration'

# Models
require 'gopad/models/auth_token'
require 'gopad/models/auth_verify'
require 'gopad/models/create_group_request'
require 'gopad/models/create_user_request'
require 'gopad/models/delete_group_from_user_request'
require 'gopad/models/delete_user_from_group_request'
require 'gopad/models/group'
require 'gopad/models/list_group_users200_response'
require 'gopad/models/list_groups200_response'
require 'gopad/models/list_providers200_response'
require 'gopad/models/list_user_groups200_response'
require 'gopad/models/list_users200_response'
require 'gopad/models/login_auth_request'
require 'gopad/models/notification'
require 'gopad/models/permit_group_user_request'
require 'gopad/models/permit_user_group_request'
require 'gopad/models/profile'
require 'gopad/models/provider'
require 'gopad/models/redirect_auth_request'
require 'gopad/models/update_profile_request'
require 'gopad/models/update_user_request'
require 'gopad/models/user'
require 'gopad/models/user_auth'
require 'gopad/models/user_group'
require 'gopad/models/validation'

# APIs
require 'gopad/api/auth_api'
require 'gopad/api/group_api'
require 'gopad/api/profile_api'
require 'gopad/api/user_api'

module Gopad
  class << self
    # Customize default settings for the SDK using block.
    #   Gopad.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
