=begin
#Gopad OpenAPI

#API definition for Gopad

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'gopad/api_client'
require 'gopad/api_error'
require 'gopad/version'
require 'gopad/configuration'

# Models
require 'gopad/models/auth_login'
require 'gopad/models/auth_token'
require 'gopad/models/auth_verify'
require 'gopad/models/general_error'
require 'gopad/models/profile'
require 'gopad/models/team'
require 'gopad/models/team_user'
require 'gopad/models/team_user_params'
require 'gopad/models/user'
require 'gopad/models/user_team_params'
require 'gopad/models/validation_error'
require 'gopad/models/validation_error_errors'

# APIs
require 'gopad/api/auth_api'
require 'gopad/api/profile_api'
require 'gopad/api/team_api'
require 'gopad/api/user_api'

module Gopad
  class << self
    # Customize default settings for the SDK using block.
    #   Gopad.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
